---
  - name: Git clone nodejs
    become: yes
    git:
      repo: 'https://github.com/GvickyGithub/nodejs-demo.git'
      dest: /data/nodejs
      update: yes
      force: yes
    ignore_errors: yes
